foreground            #BFBDB6
background            #0B0E14
cursor                #E6B450
selection_background  #131721
selection_foreground  #BFBDB6

color0  #0F131A
color1  #F07178
color2  #AAD94C
color3  #E6B450
color4  #59C2FF
color5  #D2A6FF
color6  #95E6CB
color7  #BFBDB6
color8  #6C7380
color9  #F26D78
color10 #7FD962
color11 #FFDFB3
color12 #73B8FF
color13 #DFBFFF
color14 #5CCFE6
color15 #FCFCFC

