preload = /home/jorgecab/Images/backgrounds/retro.png 
wallpaper {
    monitor = DP-1
    path = /home/jorgecab/Images/backgrounds/retro.png
}

wallpaper {
    monitor = DP-2
    path = /home/jorgecab/Images/backgrounds/retro.png
}

wallpaper {
    monitor = DP-3
    path = /home/jorgecab/Images/backgrounds/retro.png
}
