include Ayu.conf

font_family JetBrainsMono Nerd Font Mono
font_size 28
disable_ligatures always

# Emoji fallback font
#symbol_map U+1F300-U+1F6FF Noto Color Emoji
#symbol_map U+1F900-U+1F9FF Noto Color Emoji
#symbol_map U+2600-U+26FF Noto Color Emoji
#symbol_map U+2700-U+27BF Noto Color Emoji
#symbol_map U+1F680-U+1F6C5 Noto Color Emoji

shell $HOME/.local/bin/kitty-tmux 


